apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-fastapi
  labels:
    app: mlops-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-fastapi
  template:
    metadata:
      labels:
        app: mlops-fastapi
    spec:
      containers:
      - name: mlops-fastapi
        image: sumanprasad007/mlops-first-proj:v2
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-fastapi-service
spec:
  selector:
    app: mlops-fastapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
